sudo: true
notifications:
  email: false
language: node_js
node_js:
  - "node"

before_install:
  - export CC=`which clang`
  - export CXX=`which clang++`
  - sudo ln -s `which clang++` /usr/bin/clang++
  - sudo ln -s `which clang` /usr/bin/clang
  - sudo ln -s `which node` /usr/bin/node
  - sudo ln -s `which npm` /usr/bin/npm    
    
install: sudo npm install --unsafe-perm
